print("Hello" + " " "Senyo!")
print("String Manipulation Exercise")
print('String Concatenation is done with "+" Sign')
print('e.g. print("Hello" + "Senyo")')
print("New lines can be created with a backslash and n")